name: Deploy to GitHub Pages

on:
    push:
        branches: [main] # Change "main" to your branch for deployment

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20 # Adjust Node.js version as needed
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.3.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # Change "gh-pages" to your branch if different
                  FOLDER: dist # Adjust if your build output folder has a different name
